logging:
  level:
    "root": info
    "examples": trace

springturbo:
  routing-data-source:
    enabled: true
    default-data-source-name: "master"
    hikari-data-sources:
      master:
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        jdbc-url: "jdbc:mysql://192.168.31.165:3306/SpringBootPlayground?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
        username: "root"
        password: "root"
        pool-name: "master-pool"
      slave:
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        jdbc-url: "jdbc:mysql://192.168.31.166:3306/SpringBootPlayground?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
        username: "root"
        password: "root"
        pool-name: "slave-pool"

spring:
  main:
    allow-bean-definition-overriding: true
