logging:
  level:
    "root": info
    "examples": trace
    "org.springframework.security": trace

spring:
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration"

# ----------------------------------------------------------------------------------------------------------------------
# Actuator
# ----------------------------------------------------------------------------------------------------------------------
management:
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
    env:
      show-values: when_authorized
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
